//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault
    {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params
        {
            get
            {
                return this.current_paramsField;
            }
            set
            {
                this.current_paramsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name
        {
            get
            {
                return this.current_request_nameField;
            }
            set
            {
                this.current_request_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception
        {
            get
            {
                return this.nested_exceptionField;
            }
            set
            {
                this.nested_exceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service
        {
            get
            {
                return this.source_data_serviceField;
            }
            set
            {
                this.source_data_serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code
        {
            get
            {
                return this.ds_codeField;
            }
            set
            {
                this.ds_codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service
    {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace
        {
            get
            {
                return this.default_namespaceField;
            }
            set
            {
                this.default_namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name
        {
            get
            {
                return this.data_service_nameField;
            }
            set
            {
                this.data_service_nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wso2.org/dataservice", ConfigurationName="ServiceReference.BiletePortType")]
    public interface BiletePortType
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:test", ReplyAction="urn:testResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.DataServiceFault), Action="urn:testDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.testResponse> testAsync(ServiceReference.testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ins_ecerere", ReplyAction="urn:ins_ecerereResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.DataServiceFault), Action="urn:ins_ecerereDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.ins_ecerereResponse> ins_ecerereAsync(ServiceReference.ins_ecerereRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class testRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> param0;
        
        public testRequest()
        {
        }
        
        public testRequest(System.Nullable<short> param0)
        {
            this.param0 = param0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class testResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> param0;
        
        public testResponse()
        {
        }
        
        public testResponse(System.Nullable<short> param0)
        {
            this.param0 = param0;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Element
    {
        
        private string cerere_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string cerere_id
        {
            get
            {
                return this.cerere_idField;
            }
            set
            {
                this.cerere_idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ins_ecerere", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class ins_ecerereRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> vpres_rf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vidnp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vnume;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vprenume;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vcuatm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vadresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vtelefon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vemail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> vnascut_d;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vsex;
        
        public ins_ecerereRequest()
        {
        }
        
        public ins_ecerereRequest(System.Nullable<short> vpres_rf, string vidnp, string vnume, string vprenume, string vcuatm, string vadresa, string vtelefon, string vemail, System.Nullable<System.DateTime> vnascut_d, string vsex)
        {
            this.vpres_rf = vpres_rf;
            this.vidnp = vidnp;
            this.vnume = vnume;
            this.vprenume = vprenume;
            this.vcuatm = vcuatm;
            this.vadresa = vadresa;
            this.vtelefon = vtelefon;
            this.vemail = vemail;
            this.vnascut_d = vnascut_d;
            this.vsex = vsex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elements", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class ins_ecerereResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Element")]
        public ServiceReference.Element[] Element;
        
        public ins_ecerereResponse()
        {
        }
        
        public ins_ecerereResponse(ServiceReference.Element[] Element)
        {
            this.Element = Element;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface BiletePortTypeChannel : ServiceReference.BiletePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class BiletePortTypeClient : System.ServiceModel.ClientBase<ServiceReference.BiletePortType>, ServiceReference.BiletePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BiletePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(BiletePortTypeClient.GetBindingForEndpoint(endpointConfiguration), BiletePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BiletePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BiletePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BiletePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BiletePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BiletePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.testResponse> testAsync(ServiceReference.testRequest request)
        {
            return base.Channel.testAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ins_ecerereResponse> ServiceReference.BiletePortType.ins_ecerereAsync(ServiceReference.ins_ecerereRequest request)
        {
            return base.Channel.ins_ecerereAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ins_ecerereResponse> ins_ecerereAsync(System.Nullable<short> vpres_rf, string vidnp, string vnume, string vprenume, string vcuatm, string vadresa, string vtelefon, string vemail, System.Nullable<System.DateTime> vnascut_d, string vsex)
        {
            ServiceReference.ins_ecerereRequest inValue = new ServiceReference.ins_ecerereRequest();
            inValue.vpres_rf = vpres_rf;
            inValue.vidnp = vidnp;
            inValue.vnume = vnume;
            inValue.vprenume = vprenume;
            inValue.vcuatm = vcuatm;
            inValue.vadresa = vadresa;
            inValue.vtelefon = vtelefon;
            inValue.vemail = vemail;
            inValue.vnascut_d = vnascut_d;
            inValue.vsex = vsex;
            return ((ServiceReference.BiletePortType)(this)).ins_ecerereAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecureSOAP11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAP11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SecureSOAP12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAP12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecureSOAP11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://172.16.1.11:8243/services/Bilete.SecureSOAP11Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAP11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.1.11:9763/services/Bilete.SOAP11Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.SecureSOAP12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://172.16.1.11:8243/services/Bilete.SecureSOAP12Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAP12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.1.11:9763/services/Bilete.SOAP12Endpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SecureSOAP11Endpoint,
            
            SOAP11Endpoint,
            
            SecureSOAP12Endpoint,
            
            SOAP12Endpoint,
        }
    }
}
