//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cnas.md/", ConfigurationName="ServiceReference.c_aa17a14_portType")]
    public interface c_aa17a14_portType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetChangedPersonList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GetChangedPersonListResponse> GetChangedPersonListAsync(ServiceReference.GetChangedPersonListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetPersonDataForActualization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GetPersonDataForActualizationResponse> GetPersonDataForActualizationAsync(ServiceReference.GetPersonDataForActualizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConfirmReceivedPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.ConfirmReceivedPersonResponse> ConfirmReceivedPersonAsync(ServiceReference.ConfirmReceivedPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetForeignerPhysicalPersonList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.GetForeignerPhysicalPersonListResponse> GetForeignerPhysicalPersonListAsync(ServiceReference.GetForeignerPhysicalPersonListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VerifyPersonData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.VerifyPersonDataResponse> VerifyPersonDataAsync(ServiceReference.VerifyPersonDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VerifyPersonDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.VerifyPersonDocumentResponse> VerifyPersonDocumentAsync(ServiceReference.VerifyPersonDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class GetChangedPersonList
    {
        
        private string iDNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNO
        {
            get
            {
                return this.iDNOField;
            }
            set
            {
                this.iDNOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChangedPersonListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingEntity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallBasis;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallReason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.GetChangedPersonList GetChangedPersonList;
        
        public GetChangedPersonListRequest()
        {
        }
        
        public GetChangedPersonListRequest(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.GetChangedPersonList GetChangedPersonList)
        {
            this.CallingEntity = CallingEntity;
            this.CallBasis = CallBasis;
            this.CallingUser = CallingUser;
            this.CallReason = CallReason;
            this.GetChangedPersonList = GetChangedPersonList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChangedPersonListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IDNP", IsNullable=false)]
        public string[] PersonList;
        
        public GetChangedPersonListResponse()
        {
        }
        
        public GetChangedPersonListResponse(string[] PersonList)
        {
            this.PersonList = PersonList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class GetPersonDataForActualization
    {
        
        private string iDNOField;
        
        private string iDNPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNO
        {
            get
            {
                return this.iDNOField;
            }
            set
            {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IDNP
        {
            get
            {
                return this.iDNPField;
            }
            set
            {
                this.iDNPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class Person
    {
        
        private string iDNPField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string secondNameField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string birthDateStatusCodeField;
        
        private System.Nullable<System.DateTime> deathDateField;
        
        private bool deathDateFieldSpecified;
        
        private string sexCodeField;
        
        private string bloodGroupCodeField;
        
        private string birthCountryCodeField;
        
        private string birthRegionField;
        
        private string birthLocalityField;
        
        private PersonIdentDocument identDocumentField;
        
        private PersonDocument[] civilDocumentsField;
        
        private PersonAddress addressField;
        
        private PersonRelative[] relativesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNP
        {
            get
            {
                return this.iDNPField;
            }
            set
            {
                this.iDNPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SecondName
        {
            get
            {
                return this.secondNameField;
            }
            set
            {
                this.secondNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BirthDateStatusCode
        {
            get
            {
                return this.birthDateStatusCodeField;
            }
            set
            {
                this.birthDateStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> DeathDate
        {
            get
            {
                return this.deathDateField;
            }
            set
            {
                this.deathDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeathDateSpecified
        {
            get
            {
                return this.deathDateFieldSpecified;
            }
            set
            {
                this.deathDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SexCode
        {
            get
            {
                return this.sexCodeField;
            }
            set
            {
                this.sexCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BloodGroupCode
        {
            get
            {
                return this.bloodGroupCodeField;
            }
            set
            {
                this.bloodGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BirthCountryCode
        {
            get
            {
                return this.birthCountryCodeField;
            }
            set
            {
                this.birthCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BirthRegion
        {
            get
            {
                return this.birthRegionField;
            }
            set
            {
                this.birthRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BirthLocality
        {
            get
            {
                return this.birthLocalityField;
            }
            set
            {
                this.birthLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public PersonIdentDocument IdentDocument
        {
            get
            {
                return this.identDocumentField;
            }
            set
            {
                this.identDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
        public PersonDocument[] CivilDocuments
        {
            get
            {
                return this.civilDocumentsField;
            }
            set
            {
                this.civilDocumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public PersonAddress Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Relative", IsNullable=false)]
        public PersonRelative[] Relatives
        {
            get
            {
                return this.relativesField;
            }
            set
            {
                this.relativesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class PersonIdentDocument
    {
        
        private string docTypeCodeField;
        
        private System.Nullable<System.DateTime> issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private string issuedByField;
        
        private string numberField;
        
        private string seriesField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified
        {
            get
            {
                return this.expirationDateFieldSpecified;
            }
            set
            {
                this.expirationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IssuedBy
        {
            get
            {
                return this.issuedByField;
            }
            set
            {
                this.issuedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class PersonDocument
    {
        
        private string docTypeCodeField;
        
        private System.Nullable<System.DateTime> issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private System.Nullable<System.DateTime> expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private string issuedByField;
        
        private string numberField;
        
        private string seriesField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified
        {
            get
            {
                return this.expirationDateFieldSpecified;
            }
            set
            {
                this.expirationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IssuedBy
        {
            get
            {
                return this.issuedByField;
            }
            set
            {
                this.issuedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class PersonAddress
    {
        
        private string administrativeCodeField;
        
        private string blockField;
        
        private string countryField;
        
        private string countryCodeField;
        
        private string flatField;
        
        private string houseField;
        
        private string localityField;
        
        private string regionField;
        
        private string streetField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AdministrativeCode
        {
            get
            {
                return this.administrativeCodeField;
            }
            set
            {
                this.administrativeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Block
        {
            get
            {
                return this.blockField;
            }
            set
            {
                this.blockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Flat
        {
            get
            {
                return this.flatField;
            }
            set
            {
                this.flatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string House
        {
            get
            {
                return this.houseField;
            }
            set
            {
                this.houseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class PersonRelative
    {
        
        private string relativeTypeCodeField;
        
        private PersonRelativePersonalData personalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RelativeTypeCode
        {
            get
            {
                return this.relativeTypeCodeField;
            }
            set
            {
                this.relativeTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PersonRelativePersonalData PersonalData
        {
            get
            {
                return this.personalDataField;
            }
            set
            {
                this.personalDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class PersonRelativePersonalData
    {
        
        private string iDNPField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string secondNameField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private string sexCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNP
        {
            get
            {
                return this.iDNPField;
            }
            set
            {
                this.iDNPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SecondName
        {
            get
            {
                return this.secondNameField;
            }
            set
            {
                this.secondNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SexCode
        {
            get
            {
                return this.sexCodeField;
            }
            set
            {
                this.sexCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonDataForActualizationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingEntity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallBasis;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallReason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.GetPersonDataForActualization GetPersonDataForActualization;
        
        public GetPersonDataForActualizationRequest()
        {
        }
        
        public GetPersonDataForActualizationRequest(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.GetPersonDataForActualization GetPersonDataForActualization)
        {
            this.CallingEntity = CallingEntity;
            this.CallBasis = CallBasis;
            this.CallingUser = CallingUser;
            this.CallReason = CallReason;
            this.GetPersonDataForActualization = GetPersonDataForActualization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonDataForActualizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.Person Person;
        
        public GetPersonDataForActualizationResponse()
        {
        }
        
        public GetPersonDataForActualizationResponse(ServiceReference.Person Person)
        {
            this.Person = Person;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class ConfirmReceivedPerson
    {
        
        private string iDNOField;
        
        private string iDNPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNO
        {
            get
            {
                return this.iDNOField;
            }
            set
            {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IDNP
        {
            get
            {
                return this.iDNPField;
            }
            set
            {
                this.iDNPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class Result
    {
        
        private string resultCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmReceivedPersonRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingEntity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallBasis;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallReason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.ConfirmReceivedPerson ConfirmReceivedPerson;
        
        public ConfirmReceivedPersonRequest()
        {
        }
        
        public ConfirmReceivedPersonRequest(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.ConfirmReceivedPerson ConfirmReceivedPerson)
        {
            this.CallingEntity = CallingEntity;
            this.CallBasis = CallBasis;
            this.CallingUser = CallingUser;
            this.CallReason = CallReason;
            this.ConfirmReceivedPerson = ConfirmReceivedPerson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmReceivedPersonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.Result Result;
        
        public ConfirmReceivedPersonResponse()
        {
        }
        
        public ConfirmReceivedPersonResponse(ServiceReference.Result Result)
        {
            this.Result = Result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class GetForeignerPhysicalPersonList
    {
        
        private GetForeignerPhysicalPersonListPeriod periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetForeignerPhysicalPersonListPeriod Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class GetForeignerPhysicalPersonListPeriod
    {
        
        private System.DateTime dateInField;
        
        private System.DateTime dateOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateIn
        {
            get
            {
                return this.dateInField;
            }
            set
            {
                this.dateInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DateOut
        {
            get
            {
                return this.dateOutField;
            }
            set
            {
                this.dateOutField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForeignerPhysicalPersonListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingEntity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallBasis;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallReason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.GetForeignerPhysicalPersonList GetForeignerPhysicalPersonList;
        
        public GetForeignerPhysicalPersonListRequest()
        {
        }
        
        public GetForeignerPhysicalPersonListRequest(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.GetForeignerPhysicalPersonList GetForeignerPhysicalPersonList)
        {
            this.CallingEntity = CallingEntity;
            this.CallBasis = CallBasis;
            this.CallingUser = CallingUser;
            this.CallReason = CallReason;
            this.GetForeignerPhysicalPersonList = GetForeignerPhysicalPersonList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForeignerPhysicalPersonListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IDNP", IsNullable=false)]
        public string[] PersonList;
        
        public GetForeignerPhysicalPersonListResponse()
        {
        }
        
        public GetForeignerPhysicalPersonListResponse(string[] PersonList)
        {
            this.PersonList = PersonList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class VerifyPersonData
    {
        
        private string iDNPField;
        
        private VerifyPersonDataPerson personField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNP
        {
            get
            {
                return this.iDNPField;
            }
            set
            {
                this.iDNPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VerifyPersonDataPerson Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class VerifyPersonDataPerson
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyPersonDataRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingEntity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallBasis;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallReason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.VerifyPersonData VerifyPersonData;
        
        public VerifyPersonDataRequest()
        {
        }
        
        public VerifyPersonDataRequest(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.VerifyPersonData VerifyPersonData)
        {
            this.CallingEntity = CallingEntity;
            this.CallBasis = CallBasis;
            this.CallingUser = CallingUser;
            this.CallReason = CallReason;
            this.VerifyPersonData = VerifyPersonData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyPersonDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.Result Result;
        
        public VerifyPersonDataResponse()
        {
        }
        
        public VerifyPersonDataResponse(ServiceReference.Result Result)
        {
            this.Result = Result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class VerifyPersonDocument
    {
        
        private string iDNPField;
        
        private VerifyPersonDocumentDocument documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDNP
        {
            get
            {
                return this.iDNPField;
            }
            set
            {
                this.iDNPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VerifyPersonDocumentDocument Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cnas.md/")]
    public partial class VerifyPersonDocumentDocument
    {
        
        private string docTypeCodeField;
        
        private string seriesField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocTypeCode
        {
            get
            {
                return this.docTypeCodeField;
            }
            set
            {
                this.docTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyPersonDocumentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingEntity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallBasis;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallingUser;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://mconnect.gov.md")]
        public string CallReason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.VerifyPersonDocument VerifyPersonDocument;
        
        public VerifyPersonDocumentRequest()
        {
        }
        
        public VerifyPersonDocumentRequest(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.VerifyPersonDocument VerifyPersonDocument)
        {
            this.CallingEntity = CallingEntity;
            this.CallBasis = CallBasis;
            this.CallingUser = CallingUser;
            this.CallReason = CallReason;
            this.VerifyPersonDocument = VerifyPersonDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyPersonDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cnas.md/", Order=0)]
        public ServiceReference.Result Result;
        
        public VerifyPersonDocumentResponse()
        {
        }
        
        public VerifyPersonDocumentResponse(ServiceReference.Result Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface c_aa17a14_portTypeChannel : ServiceReference.c_aa17a14_portType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class c_aa17a14_portTypeClient : System.ServiceModel.ClientBase<ServiceReference.c_aa17a14_portType>, ServiceReference.c_aa17a14_portType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public c_aa17a14_portTypeClient() : 
                base(c_aa17a14_portTypeClient.GetDefaultBinding(), c_aa17a14_portTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.mconnect_port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public c_aa17a14_portTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(c_aa17a14_portTypeClient.GetBindingForEndpoint(endpointConfiguration), c_aa17a14_portTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public c_aa17a14_portTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(c_aa17a14_portTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public c_aa17a14_portTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(c_aa17a14_portTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public c_aa17a14_portTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetChangedPersonListResponse> ServiceReference.c_aa17a14_portType.GetChangedPersonListAsync(ServiceReference.GetChangedPersonListRequest request)
        {
            return base.Channel.GetChangedPersonListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetChangedPersonListResponse> GetChangedPersonListAsync(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.GetChangedPersonList GetChangedPersonList)
        {
            ServiceReference.GetChangedPersonListRequest inValue = new ServiceReference.GetChangedPersonListRequest();
            inValue.CallingEntity = CallingEntity;
            inValue.CallBasis = CallBasis;
            inValue.CallingUser = CallingUser;
            inValue.CallReason = CallReason;
            inValue.GetChangedPersonList = GetChangedPersonList;
            return ((ServiceReference.c_aa17a14_portType)(this)).GetChangedPersonListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetPersonDataForActualizationResponse> ServiceReference.c_aa17a14_portType.GetPersonDataForActualizationAsync(ServiceReference.GetPersonDataForActualizationRequest request)
        {
            return base.Channel.GetPersonDataForActualizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetPersonDataForActualizationResponse> GetPersonDataForActualizationAsync(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.GetPersonDataForActualization GetPersonDataForActualization)
        {
            ServiceReference.GetPersonDataForActualizationRequest inValue = new ServiceReference.GetPersonDataForActualizationRequest();
            inValue.CallingEntity = CallingEntity;
            inValue.CallBasis = CallBasis;
            inValue.CallingUser = CallingUser;
            inValue.CallReason = CallReason;
            inValue.GetPersonDataForActualization = GetPersonDataForActualization;
            return ((ServiceReference.c_aa17a14_portType)(this)).GetPersonDataForActualizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ConfirmReceivedPersonResponse> ServiceReference.c_aa17a14_portType.ConfirmReceivedPersonAsync(ServiceReference.ConfirmReceivedPersonRequest request)
        {
            return base.Channel.ConfirmReceivedPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ConfirmReceivedPersonResponse> ConfirmReceivedPersonAsync(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.ConfirmReceivedPerson ConfirmReceivedPerson)
        {
            ServiceReference.ConfirmReceivedPersonRequest inValue = new ServiceReference.ConfirmReceivedPersonRequest();
            inValue.CallingEntity = CallingEntity;
            inValue.CallBasis = CallBasis;
            inValue.CallingUser = CallingUser;
            inValue.CallReason = CallReason;
            inValue.ConfirmReceivedPerson = ConfirmReceivedPerson;
            return ((ServiceReference.c_aa17a14_portType)(this)).ConfirmReceivedPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetForeignerPhysicalPersonListResponse> ServiceReference.c_aa17a14_portType.GetForeignerPhysicalPersonListAsync(ServiceReference.GetForeignerPhysicalPersonListRequest request)
        {
            return base.Channel.GetForeignerPhysicalPersonListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetForeignerPhysicalPersonListResponse> GetForeignerPhysicalPersonListAsync(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.GetForeignerPhysicalPersonList GetForeignerPhysicalPersonList)
        {
            ServiceReference.GetForeignerPhysicalPersonListRequest inValue = new ServiceReference.GetForeignerPhysicalPersonListRequest();
            inValue.CallingEntity = CallingEntity;
            inValue.CallBasis = CallBasis;
            inValue.CallingUser = CallingUser;
            inValue.CallReason = CallReason;
            inValue.GetForeignerPhysicalPersonList = GetForeignerPhysicalPersonList;
            return ((ServiceReference.c_aa17a14_portType)(this)).GetForeignerPhysicalPersonListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.VerifyPersonDataResponse> ServiceReference.c_aa17a14_portType.VerifyPersonDataAsync(ServiceReference.VerifyPersonDataRequest request)
        {
            return base.Channel.VerifyPersonDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.VerifyPersonDataResponse> VerifyPersonDataAsync(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.VerifyPersonData VerifyPersonData)
        {
            ServiceReference.VerifyPersonDataRequest inValue = new ServiceReference.VerifyPersonDataRequest();
            inValue.CallingEntity = CallingEntity;
            inValue.CallBasis = CallBasis;
            inValue.CallingUser = CallingUser;
            inValue.CallReason = CallReason;
            inValue.VerifyPersonData = VerifyPersonData;
            return ((ServiceReference.c_aa17a14_portType)(this)).VerifyPersonDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.VerifyPersonDocumentResponse> ServiceReference.c_aa17a14_portType.VerifyPersonDocumentAsync(ServiceReference.VerifyPersonDocumentRequest request)
        {
            return base.Channel.VerifyPersonDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.VerifyPersonDocumentResponse> VerifyPersonDocumentAsync(string CallingEntity, string CallBasis, string CallingUser, string CallReason, ServiceReference.VerifyPersonDocument VerifyPersonDocument)
        {
            ServiceReference.VerifyPersonDocumentRequest inValue = new ServiceReference.VerifyPersonDocumentRequest();
            inValue.CallingEntity = CallingEntity;
            inValue.CallBasis = CallBasis;
            inValue.CallingUser = CallingUser;
            inValue.CallReason = CallReason;
            inValue.VerifyPersonDocument = VerifyPersonDocument;
            return ((ServiceReference.c_aa17a14_portType)(this)).VerifyPersonDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mconnect_port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mconnect_port))
            {
                return new System.ServiceModel.EndpointAddress("https://api-esb.interop.gov.md:8243/services/t/cnas.md/c_aa17a14");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return c_aa17a14_portTypeClient.GetBindingForEndpoint(EndpointConfiguration.mconnect_port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return c_aa17a14_portTypeClient.GetEndpointAddress(EndpointConfiguration.mconnect_port);
        }
        
        public enum EndpointConfiguration
        {
            
            mconnect_port,
        }
    }
}
