//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tratament.Web.Service.TreatmentTicket.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private Tratament.Web.Service.TreatmentTicket.Service.DataServiceFault.source_data_serviceType source_data_serviceField;
        
        private string ds_codeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string current_params
        {
            get
            {
                return this.current_paramsField;
            }
            set
            {
                this.current_paramsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string current_request_name
        {
            get
            {
                return this.current_request_nameField;
            }
            set
            {
                this.current_request_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string nested_exception
        {
            get
            {
                return this.nested_exceptionField;
            }
            set
            {
                this.nested_exceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Tratament.Web.Service.TreatmentTicket.Service.DataServiceFault.source_data_serviceType source_data_service
        {
            get
            {
                return this.source_data_serviceField;
            }
            set
            {
                this.source_data_serviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ds_code
        {
            get
            {
                return this.ds_codeField;
            }
            set
            {
                this.ds_codeField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="DataServiceFault.source_data_serviceType", Namespace="http://ws.wso2.org/dataservice")]
        public partial class source_data_serviceType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string locationField;
            
            private string default_namespaceField;
            
            private string descriptionField;
            
            private string data_service_nameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string location
            {
                get
                {
                    return this.locationField;
                }
                set
                {
                    this.locationField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
            public string default_namespace
            {
                get
                {
                    return this.default_namespaceField;
                }
                set
                {
                    this.default_namespaceField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
            public string description
            {
                get
                {
                    return this.descriptionField;
                }
                set
                {
                    this.descriptionField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
            public string data_service_name
            {
                get
                {
                    return this.data_service_nameField;
                }
                set
                {
                    this.data_service_nameField = value;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wso2.org/dataservice", ConfigurationName="Tratament.Web.Service.TreatmentTicket.Service.BiletePortType")]
    public interface BiletePortType
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Elements) of message ins_ecerereResponse does not match the default value (ins_ecerere)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ins_ecerere", ReplyAction="urn:ins_ecerereResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tratament.Web.Service.TreatmentTicket.Service.DataServiceFault), Action="urn:ins_ecerereDataServiceFault", Name="DataServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereResponse ins_ecerere(Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ins_ecerere", ReplyAction="urn:ins_ecerereResponse")]
        System.Threading.Tasks.Task<Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereResponse> ins_ecerereAsync(Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wso2.org/dataservice")]
    public partial class Element
    {
        
        private string cerere_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string cerere_id
        {
            get
            {
                return this.cerere_idField;
            }
            set
            {
                this.cerere_idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ins_ecerere", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class ins_ecerereRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> vpres_rf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vidnp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vnume;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vprenume;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vcuatm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vadresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vtelefon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vemail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> vnascut_d;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vsex;
        
        public ins_ecerereRequest()
        {
        }
        
        public ins_ecerereRequest(System.Nullable<short> vpres_rf, string vidnp, string vnume, string vprenume, string vcuatm, string vadresa, string vtelefon, string vemail, System.Nullable<System.DateTime> vnascut_d, string vsex)
        {
            this.vpres_rf = vpres_rf;
            this.vidnp = vidnp;
            this.vnume = vnume;
            this.vprenume = vprenume;
            this.vcuatm = vcuatm;
            this.vadresa = vadresa;
            this.vtelefon = vtelefon;
            this.vemail = vemail;
            this.vnascut_d = vnascut_d;
            this.vsex = vsex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elements", WrapperNamespace="http://ws.wso2.org/dataservice", IsWrapped=true)]
    public partial class ins_ecerereResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wso2.org/dataservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Element")]
        public Tratament.Web.Service.TreatmentTicket.Service.Element[] Element;
        
        public ins_ecerereResponse()
        {
        }
        
        public ins_ecerereResponse(Tratament.Web.Service.TreatmentTicket.Service.Element[] Element)
        {
            this.Element = Element;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BiletePortTypeChannel : Tratament.Web.Service.TreatmentTicket.Service.BiletePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiletePortTypeClient : System.ServiceModel.ClientBase<Tratament.Web.Service.TreatmentTicket.Service.BiletePortType>, Tratament.Web.Service.TreatmentTicket.Service.BiletePortType
    {
        
        public BiletePortTypeClient()
        {
        }
        
        public BiletePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BiletePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BiletePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BiletePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereResponse Tratament.Web.Service.TreatmentTicket.Service.BiletePortType.ins_ecerere(Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest request)
        {
            return base.Channel.ins_ecerere(request);
        }
        
        public Tratament.Web.Service.TreatmentTicket.Service.Element[] ins_ecerere(System.Nullable<short> vpres_rf, string vidnp, string vnume, string vprenume, string vcuatm, string vadresa, string vtelefon, string vemail, System.Nullable<System.DateTime> vnascut_d, string vsex)
        {
            Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest inValue = new Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest();
            inValue.vpres_rf = vpres_rf;
            inValue.vidnp = vidnp;
            inValue.vnume = vnume;
            inValue.vprenume = vprenume;
            inValue.vcuatm = vcuatm;
            inValue.vadresa = vadresa;
            inValue.vtelefon = vtelefon;
            inValue.vemail = vemail;
            inValue.vnascut_d = vnascut_d;
            inValue.vsex = vsex;
            Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereResponse retVal = ((Tratament.Web.Service.TreatmentTicket.Service.BiletePortType)(this)).ins_ecerere(inValue);
            return retVal.Element;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereResponse> Tratament.Web.Service.TreatmentTicket.Service.BiletePortType.ins_ecerereAsync(Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest request)
        {
            return base.Channel.ins_ecerereAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereResponse> ins_ecerereAsync(System.Nullable<short> vpres_rf, string vidnp, string vnume, string vprenume, string vcuatm, string vadresa, string vtelefon, string vemail, System.Nullable<System.DateTime> vnascut_d, string vsex)
        {
            Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest inValue = new Tratament.Web.Service.TreatmentTicket.Service.ins_ecerereRequest();
            inValue.vpres_rf = vpres_rf;
            inValue.vidnp = vidnp;
            inValue.vnume = vnume;
            inValue.vprenume = vprenume;
            inValue.vcuatm = vcuatm;
            inValue.vadresa = vadresa;
            inValue.vtelefon = vtelefon;
            inValue.vemail = vemail;
            inValue.vnascut_d = vnascut_d;
            inValue.vsex = vsex;
            return ((Tratament.Web.Service.TreatmentTicket.Service.BiletePortType)(this)).ins_ecerereAsync(inValue);
        }
    }
}
